// Package codegen turns a validated build plan into a concrete PlatformIO
// project: a platformio.ini env, a generated C++ entrypoint that constructs and
// registers the selected board/modules/policies with the kernel, and a build
// manifest. Only selected components are compiled in.
package codegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/arnal/corefw/internal/manifest"
	"github.com/arnal/corefw/internal/resolve"
)

// Options configures generation.
type Options struct {
	// OutDir is where the generated project is written.
	OutDir string
	// FirmwareDir is the path to the corefw C++ kernel/component tree, made
	// available to the generated project via lib_extra_dirs.
	FirmwareDir string
}

// Result reports what was generated.
type Result struct {
	OutDir      string
	Files       []string
	Merged      MergedBuild
	EnvName     string
	Registrations []Registration
}

// Registration is one construct+register step in the generated entrypoint.
type Registration struct {
	Var      string
	Class    string
	Header   string
	Register string
	Setters  []setterCall
	Kind     manifest.Kind
	Category string
}

type setterCall struct {
	Method string
	Arg    string
}

// Generate writes the project and returns a summary.
func Generate(plan *resolve.Plan, opts Options) (*Result, error) {
	if opts.OutDir == "" {
		return nil, fmt.Errorf("codegen: OutDir is required")
	}
	env := envName(plan.Profile.Name)
	merged := merge(plan)
	regs := registrations(plan)

	if err := os.MkdirAll(filepath.Join(opts.OutDir, "src"), 0o755); err != nil {
		return nil, err
	}

	res := &Result{OutDir: opts.OutDir, Merged: merged, EnvName: env, Registrations: regs}

	pio, err := renderPlatformIO(plan, merged, env, opts.FirmwareDir)
	if err != nil {
		return nil, err
	}
	if err := write(opts.OutDir, "platformio.ini", pio, res); err != nil {
		return nil, err
	}

	main, err := renderEntrypoint(plan, regs)
	if err != nil {
		return nil, err
	}
	if err := write(opts.OutDir, filepath.Join("src", "corefw_main.generated.cpp"), main, res); err != nil {
		return nil, err
	}
	return res, nil
}

func registrations(plan *resolve.Plan) []Registration {
	var out []Registration
	build := func(sel *resolve.Selected) {
		cg := sel.Component.Manifest.Codegen
		if cg.Class == "" {
			return // component contributes only build flags, no runtime object
		}
		reg := Registration{
			Var:      firstNonEmpty(cg.Var, slug(sel.ID())),
			Class:    cg.Class,
			Header:   cg.Header,
			Register: cg.Register,
			Kind:     sel.Component.Manifest.Type,
			Category: sel.Category,
		}
		for _, optKey := range sortedKeys(cg.Setters) {
			if v, ok := sel.Options[optKey]; ok {
				reg.Setters = append(reg.Setters, setterCall{Method: cg.Setters[optKey], Arg: cppArg(v)})
			}
		}
		out = append(out, reg)
	}
	build(plan.Board)
	for _, m := range plan.Modules {
		build(m)
	}
	for _, p := range plan.Policies {
		build(p)
	}
	return out
}

var pioTemplate = template.Must(template.New("pio").Parse(`; Generated by corefw — do not edit by hand.
; Profile: {{.Name}}
; Board:   {{.Board}}
[env:{{.Env}}]
extends = {{.BaseEnv}}
board = {{.PioBoard}}
{{- if .LdScript}}
board_build.ldscript = {{.LdScript}}
{{- end}}
{{- if .MaxSize}}
board_upload.maximum_size = {{.MaxSize}}
{{- end}}
lib_extra_dirs = {{.FirmwareDir}}
build_flags =
{{- range .Defines}}
  {{.}}
{{- end}}
{{- range .Includes}}
  -I {{.}}
{{- end}}
build_src_filter =
{{- range .SrcFilter}}
  {{.}}
{{- end}}
lib_deps =
{{- range .LibDeps}}
  {{.}}
{{- end}}
`))

func renderPlatformIO(plan *resolve.Plan, mb MergedBuild, env, firmwareDir string) (string, error) {
	board := plan.Board.Component.Manifest.Board
	var defines []string
	for _, k := range mb.sortedDefines() {
		v := mb.Defines[k]
		if v == "" {
			defines = append(defines, "-D "+k)
		} else {
			defines = append(defines, fmt.Sprintf("-D %s=%s", k, v))
		}
	}
	data := struct {
		Name, Board, Env, BaseEnv, PioBoard, LdScript, FirmwareDir string
		MaxSize                                                    int
		Defines, Includes, SrcFilter, LibDeps                      []string
	}{
		Name:        plan.Profile.Name,
		Board:       plan.Board.ID(),
		Env:         env,
		BaseEnv:     board.PlatformIO.BaseEnv,
		PioBoard:    board.PlatformIO.Board,
		LdScript:    board.PlatformIO.LdScript,
		MaxSize:     board.PlatformIO.MaxSize,
		FirmwareDir: firmwareDir,
		Defines:     defines,
		Includes:    mb.Includes,
		SrcFilter:   mb.SrcFilter,
		LibDeps:     mb.LibDeps,
	}
	var buf bytes.Buffer
	if err := pioTemplate.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func write(outDir, rel, content string, res *Result) error {
	full := filepath.Join(outDir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		return err
	}
	res.Files = append(res.Files, rel)
	return nil
}

func envName(name string) string {
	if name == "" {
		return "corefw"
	}
	return "corefw_" + slug(name)
}

func slug(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return strings.Trim(b.String(), "_")
}

// cppArg renders a validated option value as a C++ literal.
func cppArg(v any) string {
	switch t := v.(type) {
	case string:
		return strconv.Quote(t)
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int64:
		return strconv.FormatInt(t, 10)
	case int:
		return strconv.Itoa(t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	default:
		return fmt.Sprintf("%v", t)
	}
}

// defineValue renders a value for a -D define (no C++ quoting).
func defineValue(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case bool:
		if t {
			return "1"
		}
		return "0"
	case int64:
		return strconv.FormatInt(t, 10)
	case int:
		return strconv.Itoa(t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	default:
		return fmt.Sprintf("%v", t)
	}
}

func quote(s string) string { return `'"` + s + `"'` }

func firstNonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func sortedKeys(m map[string]string) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}
