package codegen

import (
	"bytes"
	"sort"

	"github.com/arnal/corefw/internal/resolve"
)

// renderEntrypoint constructs the composition root. It builds the board,
// modules and policies chosen by the profile and registers them with the
// kernel. The kernel owns the main loop, radio scheduling and power
// coordination; generated code only wires objects together — it never touches
// the radio directly. This mirrors the architecture principle: the kernel
// provides mechanisms, components and policies define the resulting device.
func renderEntrypoint(plan *resolve.Plan, regs []Registration) (string, error) {
	// Build the body by hand for full control (templates get awkward with the
	// per-registration setter grouping).
	var body bytes.Buffer
	for _, r := range regs {
		body.WriteString("\n  // ")
		body.WriteString(string(r.Kind))
		if r.Category != "" {
			body.WriteString(" (" + r.Category + ")")
		}
		body.WriteString(": " + r.Class + "\n")
		for _, s := range r.Setters {
			body.WriteString("  " + r.Var + "." + s.Method + "(" + s.Arg + ");\n")
		}
		if r.Register != "" {
			body.WriteString("  kernel." + r.Register + "(&" + r.Var + ");\n")
		}
	}

	var decls bytes.Buffer
	for _, r := range regs {
		decls.WriteString("static " + r.Class + " " + r.Var + ";\n")
	}

	includes := collectHeaders(regs)
	var inc bytes.Buffer
	for _, h := range includes {
		inc.WriteString("#include <" + h + ">\n")
	}

	// LDF primer: the shared platform main pulls in the board's display driver via
	// a macro (#include DISPLAY_HEADER), which PlatformIO's library dependency
	// finder cannot expand — so it never discovers the display lib (Adafruit GFX,
	// etc.). Including that header literally here (the composition root is project
	// source and always LDF-scanned) puts the lib on the build's include path. Only
	// emitted when a selected module uses a display and the board provides one.
	inc.WriteString(displayPrimer(plan))

	out := "// Generated by corefw — do not edit by hand.\n" +
		"// Profile: " + plan.Profile.Name + "\n" +
		"//\n" +
		"// This file is the composition root. The corefw kernel provides the mechanisms\n" +
		"// (protocol runtime, radio scheduler, crypto, power coordinator); the objects\n" +
		"// registered below define what this particular device is.\n" +
		"#include <corefw/Kernel.h>\n" +
		inc.String() +
		"\nusing namespace corefw;\n\n" +
		decls.String() +
		"\n// corefw_compose is called once by the kernel at startup, before the radio is\n" +
		"// brought up. It must not block or transmit. (Qualified so it defines the\n" +
		"// declaration in namespace corefw, not a global overload.)\n" +
		"void corefw::corefw_compose(Kernel& kernel) {" +
		body.String() +
		"}\n"
	return out, nil
}

// displayPrimer returns a guarded literal include of the board's display driver
// header, or "" when no selected module uses a display or the board provides
// none. See the call site for why this is needed (macro-include vs LDF).
func displayPrimer(plan *resolve.Plan) string {
	board := plan.Board.Component.Manifest.Board
	if board == nil || board.Display == nil || board.Display.Header == "" {
		return ""
	}
	usesDisplay := false
	for _, m := range plan.Modules {
		if m.Component.Manifest.Build.UsesDisplay {
			usesDisplay = true
			break
		}
	}
	if !usesDisplay {
		return ""
	}
	return "#if defined(COREFW_TARGET)\n#include <" + board.Display.Header + ">  // LDF primer (see below)\n#endif\n"
}

func collectHeaders(regs []Registration) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range regs {
		if r.Header != "" && !seen[r.Header] {
			seen[r.Header] = true
			out = append(out, r.Header)
		}
	}
	sort.Strings(out)
	return out
}
