// The corefw kernel.
//
// The kernel provides the mechanisms shared by almost every node — protocol
// runtime, radio scheduling, cryptographic identity, queues, event dispatch,
// power coordination, airtime enforcement — and stays conservative and slow to
// change. Components and policies, registered here, define the resulting
// device. The kernel deliberately does not assume the device is a repeater,
// companion, sensor or tracker.
#pragma once

#include <corefw/Board.h>
#include <corefw/Event.h>
#include <corefw/Mesh.h>
#include <corefw/Module.h>
#include <corefw/Power.h>

namespace corefw {

// Maximum number of modules a single image may register. Kept small and static
// to avoid heap churn on constrained MCUs.
inline constexpr int kMaxModules = 16;

class Kernel {
 public:
  // --- Registration API (driven by generated composition code) ------------
  void registerBoard(Board* board) { board_ = board; }

  void registerModule(Module* module) {
    if (module_count_ < kMaxModules) modules_[module_count_++] = module;
  }

  void setPowerPolicy(PowerPolicy* policy) { power_policy_ = policy; }

  // --- Accessors ----------------------------------------------------------
  Board* board() { return board_; }
  PowerPolicy* powerPolicy() { return power_policy_; }
  int moduleCount() const { return module_count_; }
  Module* module(int i) { return modules_[i]; }

  // --- Runtime ------------------------------------------------------------
  // begin() brings up the board, wires services and drives each module through
  // configure -> initialize -> start. Implemented in the kernel .cpp; declared
  // here as the stable entrypoint the platform's setup() calls.
  void begin(MeshService& mesh, PowerCoordinator& power);

  // dispatch delivers an event to every registered module.
  void dispatch(const Event& e) {
    for (int i = 0; i < module_count_; ++i) modules_[i]->onEvent(e);
  }

  // applyAdvertDecorators lets every registered module enrich an advert before
  // it is signed and sent. The platform's advert-build path calls this after
  // populating the base fields (type, name, location). Extension components
  // override Module::decorateAdvert to hook in; nothing else needs to know they
  // exist. See components/extensions/ for the pattern.
  void applyAdvertDecorators(proto::AdvertData& ad) {
    for (int i = 0; i < module_count_; ++i) modules_[i]->decorateAdvert(ad);
  }

  // setConfigVar offers a custom-var write to each module; the first to claim
  // the key wins. getConfigVars collects every module's "name:value" pairs into
  // a comma-separated list (companion custom-var format), respecting `cap`.
  // These back the companion CMD_SET_CUSTOM_VAR / CMD_GET_CUSTOM_VAR path so
  // extensions can expose runtime config without new command codes.
  bool setConfigVar(const char* name, const char* value) {
    for (int i = 0; i < module_count_; ++i) {
      if (modules_[i]->setConfigVar(name, value)) return true;
    }
    return false;
  }
  size_t getConfigVars(char* out, size_t cap) {
    size_t n = 0;
    for (int i = 0; i < module_count_; ++i) {
      char tmp[96];
      size_t w = modules_[i]->getConfigVars(tmp, sizeof(tmp));
      if (w == 0) continue;
      if (n > 0 && n < cap) out[n++] = ',';  // separate module contributions
      for (size_t k = 0; k < w && n < cap; ++k) out[n++] = tmp[k];
    }
    return n;
  }

 private:
  Board* board_ = nullptr;
  PowerPolicy* power_policy_ = nullptr;
  Module* modules_[kMaxModules] = {};
  int module_count_ = 0;
};

// Generated by corefw for each profile: constructs and registers the selected
// board, modules and policies. Defined in src/corefw_main.generated.cpp.
void corefw_compose(Kernel& kernel);

}  // namespace corefw
