properties:
  low_battery:
    type: integer
    minimum: 1
    maximum: 99
    default: 30
  critical_battery:
    type: integer
    minimum: 1
    maximum: 99
    default: 15
  sleep_duration:
    type: duration
    default: 1h
required:
  - low_battery
  - critical_battery
rules:
  - less_than: [critical_battery, low_battery]
